"""
pkgdb - Track PyPI package download statistics.

Reads published packages from packages.json, fetches download statistics
via pypistats, stores data in SQLite, and generates HTML reports.
"""

__version__ = "0.3.0"

# Re-export public API from submodules
from .api import (
    aggregate_env_stats,
    check_package_exists,
    fetch_all_package_stats,
    fetch_daily_downloads,
    fetch_os_stats,
    fetch_package_stats,
    fetch_pypi_releases,
    fetch_python_versions,
    fetch_user_packages,
)
from .badges import (
    BADGE_COLORS,
    generate_badge_svg,
    generate_downloads_badge,
)
from .checks import (
    detect_anomaly,
    detect_milestones,
    weekly_totals,
)
from .cli import (
    DEFAULT_PACKAGES_FILE,
    apply_config,
    import_packages_from_file,
    load_packages,
    load_packages_from_file,
    main,
)
from .config import (
    PkgdbConfig,
    get_config_path,
    load_config,
)
from .db import (
    DEFAULT_DB_FILE,
    DEFAULT_REPORT_FILE,
    REPO_SOURCE_DISCOVER,
    REPO_SOURCE_MANUAL,
    REPO_SOURCE_PACKAGE,
    add_package,
    add_package_tag,
    add_repo,
    cleanup_orphaned_stats,
    clear_ci_status,
    get_ci_status,
    get_repo_packages,
    get_repos,
    link_package_repo,
    normalize_repo_key,
    prune_ci_status,
    remove_repo,
    seed_repos_from_cache,
    set_repo_enabled,
    store_ci_status,
    get_all_github_releases,
    get_all_history,
    get_all_pypi_releases,
    get_cached_env_summary,
    get_cached_os_stats,
    get_cached_python_versions,
    get_config_dir,
    get_daily_downloads,
    get_database_stats,
    get_db,
    get_db_connection,
    get_github_releases,
    get_github_stats_history,
    get_milestone_high_water,
    set_milestone_high_water,
    get_latest_stats,
    get_package_history,
    get_package_tags,
    get_packages,
    get_packages_for_tag,
    get_tags_map,
    get_next_update_seconds,
    get_packages_needing_update,
    get_pypi_releases,
    get_stats_with_growth,
    init_db,
    is_tracked,
    prune_old_stats,
    record_fetch_attempt,
    remove_package,
    remove_package_tag,
    store_daily_downloads,
    store_env_stats,
    store_github_releases,
    store_github_stats_snapshot,
    store_pypi_releases,
    store_stats,
    store_stats_batch,
)
from .github import (
    CI_CACHE_TTL_MINUTES,
    CI_RUN_WINDOW,
    GITHUB_CACHE_TTL_HOURS,
    RepoResult,
    RepoStats,
    WorkflowRun,
    clear_github_cache,
    extract_github_url,
    fetch_authenticated_login,
    fetch_default_branch,
    fetch_github_releases,
    fetch_package_github_stats,
    fetch_repo_stats,
    fetch_user_repos,
    fetch_workflow_count,
    fetch_workflow_runs,
    get_github_cache_stats,
    get_github_token,
    latest_run_per_workflow,
    parse_github_url,
    parse_workflow_runs,
)
from .export import (
    export_csv,
    export_json,
    export_markdown,
)
from .logging import (
    get_logger,
    setup_logging,
)
from .reports import (
    generate_html_report,
    generate_package_html_report,
    generate_project_html_report,
    make_svg_pie_chart,
)
from .service import (
    CIEntry,
    CIResult,
    FetchResult,
    PackageDetails,
    PackageInfo,
    PackageStatsService,
    SyncResult,
)
from .types import (
    CI_STATE_FAIL,
    CI_STATE_NO_RUNS,
    CI_STATE_PASS,
    CI_STATE_RUNNING,
    CI_STATE_UNKNOWN,
    CIRun,
    CategoryDownloads,
    CheckEvent,
    DailyDownload,
    DatabaseInfo,
    EnvSummary,
    GitHubRelease,
    HistoryRecord,
    PackageStats,
    PyPIRelease,
    RepoRecord,
    StatsWithGrowth,
)
from .utils import (
    calculate_growth,
    daily_window_sums,
    make_sparkline,
    parse_date_arg,
    validate_output_path,
    validate_package_name,
)

__all__ = [
    # Version
    "__version__",
    # API
    "aggregate_env_stats",
    "check_package_exists",
    "fetch_all_package_stats",
    "fetch_daily_downloads",
    "fetch_os_stats",
    "fetch_package_stats",
    "fetch_pypi_releases",
    "fetch_python_versions",
    "fetch_user_packages",
    # Badges
    "BADGE_COLORS",
    "generate_badge_svg",
    "generate_downloads_badge",
    # Checks
    "detect_anomaly",
    "detect_milestones",
    "weekly_totals",
    # CLI
    "DEFAULT_PACKAGES_FILE",
    "apply_config",
    "import_packages_from_file",
    "load_packages",
    "load_packages_from_file",
    "main",
    # Config
    "PkgdbConfig",
    "get_config_path",
    "load_config",
    # Database
    "DEFAULT_DB_FILE",
    "DEFAULT_REPORT_FILE",
    "REPO_SOURCE_DISCOVER",
    "REPO_SOURCE_MANUAL",
    "REPO_SOURCE_PACKAGE",
    "add_package",
    "add_package_tag",
    "add_repo",
    "cleanup_orphaned_stats",
    "clear_ci_status",
    "get_ci_status",
    "get_repo_packages",
    "get_repos",
    "link_package_repo",
    "normalize_repo_key",
    "prune_ci_status",
    "remove_repo",
    "seed_repos_from_cache",
    "set_repo_enabled",
    "store_ci_status",
    "get_all_github_releases",
    "get_all_history",
    "get_all_pypi_releases",
    "get_cached_env_summary",
    "get_cached_os_stats",
    "get_cached_python_versions",
    "get_config_dir",
    "get_daily_downloads",
    "get_database_stats",
    "get_db",
    "get_db_connection",
    "get_github_releases",
    "get_github_stats_history",
    "get_milestone_high_water",
    "set_milestone_high_water",
    "get_latest_stats",
    "get_package_history",
    "get_package_tags",
    "get_packages",
    "get_packages_for_tag",
    "get_tags_map",
    "get_next_update_seconds",
    "get_packages_needing_update",
    "get_pypi_releases",
    "get_stats_with_growth",
    "init_db",
    "is_tracked",
    "prune_old_stats",
    "record_fetch_attempt",
    "remove_package",
    "remove_package_tag",
    "store_daily_downloads",
    "store_env_stats",
    "store_github_releases",
    "store_github_stats_snapshot",
    "store_pypi_releases",
    "store_stats",
    "store_stats_batch",
    # GitHub
    "CI_CACHE_TTL_MINUTES",
    "CI_RUN_WINDOW",
    "GITHUB_CACHE_TTL_HOURS",
    "RepoResult",
    "RepoStats",
    "WorkflowRun",
    "clear_github_cache",
    "extract_github_url",
    "fetch_authenticated_login",
    "fetch_default_branch",
    "fetch_github_releases",
    "fetch_package_github_stats",
    "fetch_repo_stats",
    "fetch_user_repos",
    "fetch_workflow_count",
    "fetch_workflow_runs",
    "get_github_cache_stats",
    "get_github_token",
    "latest_run_per_workflow",
    "parse_github_url",
    "parse_workflow_runs",
    # Export
    "export_csv",
    "export_json",
    "export_markdown",
    # Logging
    "get_logger",
    "setup_logging",
    # Reports
    "generate_html_report",
    "generate_package_html_report",
    "generate_project_html_report",
    "make_svg_pie_chart",
    # Service
    "CIEntry",
    "CIResult",
    "FetchResult",
    "PackageDetails",
    "PackageInfo",
    "PackageStatsService",
    "SyncResult",
    # Types
    "CI_STATE_FAIL",
    "CI_STATE_NO_RUNS",
    "CI_STATE_PASS",
    "CI_STATE_RUNNING",
    "CI_STATE_UNKNOWN",
    "CIRun",
    "CategoryDownloads",
    "CheckEvent",
    "DailyDownload",
    "DatabaseInfo",
    "EnvSummary",
    "GitHubRelease",
    "HistoryRecord",
    "PackageStats",
    "PyPIRelease",
    "RepoRecord",
    "StatsWithGrowth",
    # Utils
    "calculate_growth",
    "daily_window_sums",
    "make_sparkline",
    "parse_date_arg",
    "validate_output_path",
    "validate_package_name",
]
